export default {
  'hotspot-element': 'Hotspot Element',
  'driving-conversions-with-ctas': 'Driving Conversions with CTAs',
  'creating-and-animating-creative-fonts': 'Creating and Animating Creative Fonts',
  'interaction-elements-how-to-use-the-property-panel': 'Interaction Elements – How to Use the Property Panel',
  'dynamic-ctas-to-boost-conversions': 'Dynamic CTAs to Boost Conversions',
  'getting-started-with-widgets-and-elements': 'Getting Started with Widgets and Elements',
  'capturing-leads-from-videos': 'Capturing Leads from Videos',
  'making-amazing-video-surveys-with-hotspots': 'Making Amazing Video Surveys with Hotspots',
  'html-element': 'HTML Element',
  'adding-video-overlays': 'Adding Video Overlays',
  'generating-leads-with-adaptive-intro-forms': 'Generating Leads with Adaptive Intro Forms',
  'collaborating-on-videos': 'Collaborating on Videos',
  'add-or-edit-interactivity': 'Add or Edit Interactivity',
  'creating-action-buttons-in-cinema8-creative-studio': 'Creating Action Buttons in Cinema8 Creative Studio',
  'examples-of-growing-your-business-with-video': 'Examples of Growing Your Business with Video',
  'introducing-interactive-growth-tools': 'Introducing Interactive Growth Tools',
  'using-introduction-forms': 'Using Introduction Forms',
};
